import { Schema, model, type Document, type Types } from 'mongoose';

//DEVICES THAT SKIP THE CODE.
//
//Not a security boundary. `deviceId` is generated by the app and sent by the
//caller, so anyone can claim any value — all it decides is whether a one-time
//code is required. The password is still checked every time.
//
//What it buys is friction: a phone someone uses weekly never sees a code
//again, so the code stays meaningful when it does appear.

export interface TrustedDeviceDocument extends Document {
  _id: Types.ObjectId;
  user: Types.ObjectId;
  deviceId: string;
  //"Android 14 · Tecno" — shown in settings so a user can recognise which
  //phone a row refers to before revoking it.
  label: string;
  lastSeenAt: Date;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

const trustedDeviceSchema = new Schema<TrustedDeviceDocument>(
  {
    user: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    deviceId: { type: String, required: true },
    label: { type: String, default: 'Unknown device', maxlength: 80 },
    lastSeenAt: { type: Date, default: Date.now },
    expiresAt: { type: Date, required: true },
  },
  { timestamps: true }
);

//One row per device per user. The unique index is what makes "trust this
//device" an upsert rather than a duplicate on every login.
trustedDeviceSchema.index({ user: 1, deviceId: 1 }, { unique: true });

//Trust lapses on its own after the window. A phone untouched for three months
//asks for a code once, then is trusted again.
trustedDeviceSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

export const TrustedDevice = model<TrustedDeviceDocument>(
  'TrustedDevice',
  trustedDeviceSchema
);
